development:
  adapter: postgresql
  encoding: unicode
  database: lester_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: lester_test
  pool: 5
  host: localhost
